name = "makoto-redirect"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = false

# Redirect both domains to usemakoto.dev
# Ensure both domains are active in your Cloudflare account
routes = [
  { pattern = "dpl.dev/*", zone_name = "dpl.dev" },
  { pattern = "dsla.dev/*", zone_name = "dsla.dev" }
]
